import os
from time import sleep
from sty import fg, bg, ef, rs
os.system("cls||clear")

print('                                        ')
sleep(0.5)
print(fg(62)+'             *     ,MMM8&&&.            *'+ fg.rs)
sleep(0.5)
print(fg(62)+'                  MMMM88&&&&&    .'+ fg.rs)
sleep(0.5)
print(fg(62)+'                 MMMM88&&&&&&&	'+ fg.rs)
sleep(0.5)
print(fg(62)+'     *           MMM88&&&&&&&&	'+ fg.rs)
sleep(0.5)
print(fg(62)+'                 MMM88&&&&&&&&	'+ fg.rs)
sleep(0.5)
print(fg(62)+"                 'MMM88&&&&&&'	"+ fg.rs)
sleep(0.5)
print(fg(62)+"                   'MMM8&&&'      * "+ fg.rs)
sleep(0.5)
print(fg(226)+'          |\___/|	                        '+ fg.rs)
sleep(0.5)
print(fg(226)+'          )     (            '+ fg(62)+' .          *  '+ fg.rs)
sleep(0.5)
print(fg(226)+'         =\     /=							'+ fg.rs)
sleep(0.5)
print(fg(226)+'           )===(       '+ fg(62)+'*						'+ fg.rs)
sleep(0.5)
print(fg(226)+'          /     \							'+ fg.rs)
sleep(0.5)
print(fg(226)+'          |     |							'+ fg.rs)
sleep(0.5)
print(fg(226)+'         /       \							'+ fg.rs)
sleep(0.5)
print(fg(226)+'         \       /							'+ fg.rs)
sleep(0.5)
print(fg(202)+'  _/\_/\_/'+fg(226)+'\__  _/'+fg(202)+'_/\_/\_/\_/\_/\_/\_/\_/\_/\_	'+ fg.rs)
sleep(0.5)
print(fg(202)+'  |  |  |  |'+fg(226)+'( (  '+fg(202)+'|  |  |  |  |  |  |  |  |  |	'+ fg.rs)
sleep(0.5)
print(fg(202)+'  |  |  |  |'+fg(226)+' ) )'+fg(202)+' |  |  |  |  |  |  |  |  |  |	'+ fg.rs)
sleep(0.5)
print(fg(202)+'  |  |  |  |'+fg(226)+'(_(  '+fg(202)+'|  |  |  |  |  |  |  |  |  |	'+ fg.rs)
sleep(0.5)
print(fg(202)+'  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |	'+ fg.rs)
sleep(0.5)
print(fg(202)+'  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |	'+ fg.rs)
sleep(5)
print("\033[0;0H")
os.system("cls||clear")
print('                                        ')
sleep(0.5)
print(fg(62)+"             *     ,MMM8&&&.            * "+ fg.rs)
sleep(0.5)
print(fg(62)+"                  MMMM88&&&&&    .        "+ fg.rs)
sleep(0.5)
print(fg(62)+"                 MMMM88&&&&&&&            "+ fg.rs)
sleep(0.5)
print(fg(62)+"     *           MMM88&&&&&&&&           "+ fg.rs)
sleep(0.5)
print(fg(62)+"                 MMM88&&&&&&&&           "+ fg.rs)
sleep(0.5)
print(fg(62)+"                 'MMM88&&&&&&'           "+ fg.rs)
sleep(0.5)
print(fg(62)+"                   'MMM8&&&'      *      "+ fg.rs)
sleep(0.5)
print(fg(226)+"          |\___/|                        "+ fg.rs)
sleep(0.5)
print(fg(226)+"         =) ^Y^ (=          "+fg(62)+"  .              ' "+ fg.rs)
sleep(0.5)
print(fg(226)+"          \  ^  /                               "+ fg.rs)
sleep(0.5)
print(fg(226)+"           )=*=(     "+fg(62)+"  *                 "+ fg.rs)
sleep(0.5)
print(fg(226)+"          /     \                        "+ fg.rs)
sleep(0.5)
print(fg(226)+"          |     |                        "+ fg.rs)
sleep(0.5)
print(fg(226)+"         /| | | |\                       "+ fg.rs)
sleep(0.5)
print(fg(226)+"         \| | |_|/\                      "+ fg.rs)
sleep(0.5)
print(fg(202)+"  _/\_/\_"+fg(226)+"//_// ___/"+fg(202)+"\_/\_/\_/\_/\_/\_/\_/\_/\_  "+ fg.rs)
sleep(0.5)
print(fg(202)+"  |  |  |  | "+fg(226)+"\_) "+fg(202)+"|  |  |  |  |  |  |  |  |  |    "+ fg.rs)
sleep(0.5)
print(fg(202)+"  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |    "+ fg.rs)
sleep(0.5)
print(fg(202)+"  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |    "+ fg.rs)
sleep(0.5)
print(fg(202)+"  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |    "+ fg.rs)
sleep(0.5)
print(fg(202)+"  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |    "+ fg.rs)
sleep(5)
print("\033[0;0H")
os.system("cls||clear")
print('                                        ')
sleep(0.5)
print(fg(62)+"             *     ,MMM8&&&.            * "+ fg.rs)
sleep(0.5)
print(fg(62)+"                  MMMM88&&&&&    .       "+ fg.rs)
sleep(0.5)
print(fg(62)+"                 MMMM88&&&&&&&           "+ fg.rs)
sleep(0.5)
print(fg(62)+"     *           MMM88&&&&&&&&           "+ fg.rs)
sleep(0.5)
print(fg(62)+"                 MMM88&&&&&&&&           "+ fg.rs)
sleep(0.5)
print(fg(62)+"                 'MMM88&&&&&&'           "+ fg.rs)
sleep(0.5)
print(fg(62)+"                   'MMM8&&&'      *  "+fg(199)+"  _    "+ fg.rs)
sleep(0.5)
print(fg(226)+"          |\___/|                   "+fg(199)+"   \\\\    "+ fg.rs)
sleep(0.5)
print(fg(226)+"         =) ^Y^ (=  "+fg(199)+" |\_/|              ||    " +fg(62)+" '"+ fg.rs)
sleep(0.5)
print(fg(226)+"          \  ^  /   "+fg(199)+" )a a '"+'._.-""""-.  // '+ fg.rs)
sleep(0.5)
print(fg(226)+"           )=*=(    "+fg(199)+"=\T_= /    ~  ~  \//     "+ fg.rs)
sleep(0.5)
print(fg(226)+"          /     \    "+fg(199)+' `"`\   ~   / ~  /      '+ fg.rs)
sleep(0.5)
print(fg(226)+"          |     |     "+fg(199)+"    |~   \ |  ~/       "+ fg.rs)
sleep(0.5)
print(fg(226)+"         /| | | |\     "+fg(199)+"    \  ~/- \ ~\       "+ fg.rs)
sleep(0.5)
print(fg(226)+"         \| | |_|/|    "+fg(199)+"    || |  // /`       "+ fg.rs)
sleep(0.5)
print(fg(202)+"  _/\_/\_"+fg(226)+"//_// __//"+fg(202)+"\_/\_/\_"+fg(199)+"((_|"+fg(202)+"\\"+fg(199)+"((_/"+fg(202)+"/\_/\_/\_"+ fg.rs)
sleep(0.5)
print(fg(202)+"  |  |  |  | "+fg(226)+"\_) "+fg(202)+"|  |  |  |  |  |  |  |  |  | "+ fg.rs)
sleep(0.5)
print(fg(202)+"  |  |  |  |  |  |  |  |  |  |  |  |  |  |  | "+ fg.rs)
sleep(0.5)
print(fg(202)+"  |  |  |  |  |  |  |  |  |  |  |  |  |  |  | "+ fg.rs)
sleep(0.5)
print(fg(202)+"  |  |  |  |  |  |  |  |  |  |  |  |  |  |  | "+ fg.rs)
sleep(0.5)
print(fg(202)+"  |  |  |  |  |  |  |  |  |  |  |  |  |  |  | "+ fg.rs)
sleep(5)
print("\033[0;0H")
os.system("cls||clear")
print('                                        ')   
sleep(0.5)
print(fg(62)+"             *     ,MMM8&&&.            * "+ fg.rs)
sleep(0.5)
print(fg(62)+"                  MMMM88&&&&&    .       "+ fg.rs)
sleep(0.5)
print(fg(62)+"                 MMMM88&&&&&&&           "+ fg.rs)
sleep(0.5)
print(fg(62)+"     *           MMM88&&&&&&&&           "+ fg.rs)
sleep(0.5)
print(fg(62)+"                 MMM88&&&&&&&&           "+ fg.rs)
sleep(0.5)
print(fg(62)+"                 'MMM88&&&&&&'           "+ fg.rs)
sleep(0.5)
print(fg(62)+"                   'MMM8&&&'      *      "+ fg.rs)
sleep(0.5)
print(fg(226)+"          |\___/|  "+fg(199)+"   /\___/\            "+ fg.rs)
sleep(0.5)
print(fg(226)+"          )     (  "+fg(199)+"   )    ~( .      " +fg(62)+"  '    "+ fg.rs) 
sleep(0.5) 
print(fg(226)+"         =\     /= "+fg(199)+"  =\~    /=           "+ fg.rs)
sleep(0.5)
print(fg(226)+"           )===(    "+fg(199)+"   ) ~ (             "+ fg.rs)
sleep(0.5)
print(fg(226)+"          /     \   "+fg(199)+"  /     \            "+ fg.rs)
sleep(0.5)
print(fg(226)+"          |     |  "+fg(199)+"   ) ~   (            "+ fg.rs)
sleep(0.5)
print(fg(226)+"         /       \  "+fg(199)+" /     ~ \           "+ fg.rs)
sleep(0.5)
print(fg(226)+"         \       /  "+fg(199)+" \~     ~/           "+ fg.rs)
sleep(0.5)
print(fg(226)+"  _/\_/\_/"+fg(226)+"\__  _/"+fg(202)+"_/\_/"+fg(199)+"\__~__/"+fg(202)+"_/\_/\_/\_/\_/\_    "+ fg.rs)
sleep(0.5)
print(fg(202)+"  |  |  |  |"+fg(226)+"( (  "+fg(202)+"|  |  | "+fg(199)+"))"+fg(202)+"  |  |  |  |  |  |    "+ fg.rs)
sleep(0.5)
print(fg(202)+"  |  |  |  |"+fg(226)+" ) ) "+fg(202)+"|  |  |"+fg(199)+"//"+fg(202)+"|  |  |  |  |  |  |    "+ fg.rs)
sleep(0.5)
print(fg(202)+"  |  |  |  |"+fg(226)+"(_(  "+fg(202)+"|  |  "+fg(199)+"(( "+fg(202)+"|  |  |  |  |  |  |    "+ fg.rs)
sleep(0.5)
print(fg(202)+"  |  |  |  |  |  |  |  |"+fg(199)+"\)"+fg(202)+"|  |  |  |  |  |  |    "+ fg.rs)
sleep(0.5)
print(fg(202)+"  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |    "+ fg.rs)
sleep(5)
print("\033[0;0H")
os.system("cls||clear")
print('                                        '+ fg.rs) 
sleep(0.5)
print(fg(62)+"             *     ,MMM8&&&.            * "+ fg.rs)
sleep(0.5)
print(fg(62)+"                  MMMM88&&&&&    .           "+ fg.rs)
sleep(0.5)
print(fg(62)+"                 MMMM88&&&&&&&               "+ fg.rs)
sleep(0.5)
print(fg(62)+"     *           MMM88&&&&&&&&               "+ fg.rs)
sleep(0.5)
print(fg(62)+"                 MMM88&&&&&&&&               "+ fg.rs)
sleep(0.5)
print(fg(62)+"                 'MMM88&&&&&&'               "+ fg.rs)
sleep(0.5)
print(fg(62)+"                   'MMM8&&&'      *          "+ fg.rs)
sleep(0.5)
print(fg(226)+"           /\/|_   "+fg(199)+"   __/\\                  "+ fg.rs) 
sleep(0.5)   
print(fg(226)+"          /    -\  "+fg(199)+"  /-   ~\  "+fg(62)+".              ' "+ fg.rs)
sleep(0.5)
print(fg(226)+"          \    = Y "+fg(199)+"=T_ =   /                     "+ fg.rs)
sleep(0.5)
print(fg(226)+"           )==*(`   "+fg(199)+"  `) ~ \                     "+ fg.rs)
sleep(0.5)
print(fg(226)+"          /     \   "+fg(199)+"  /     \                    "+ fg.rs)
sleep(0.5)
print(fg(226)+"          |     |   "+fg(199)+"  ) ~   (                    "+ fg.rs)
sleep(0.5)
print(fg(226)+"         /       \  "+fg(199)+" /     ~ \                   "+ fg.rs)
sleep(0.5)
print(fg(226)+"         \       /   "+fg(199)+"\~     ~/                   "+ fg.rs)
sleep(0.5)
print(fg(226)+"  _/\_/\_/"+fg(226)+"\__  _/"+fg(202)+"_/\_/"+fg(199)+"\__~__/"+fg(202)+"_/\_/\_/\_/\_/\_    "+ fg.rs)
sleep(0.5)
print(fg(202)+"  |  |  |  | "+fg(226)+") ) "+fg(202)+"|  |  | "+fg(199)+"((  "+fg(202)+"|  |  |  |  |  |    "+ fg.rs)
sleep(0.5)
print(fg(202)+"  |  |  |  |"+fg(226)+"( (  "+fg(202)+"|  |  |  "+fg(199)+'\\\\' +fg(202)+"|  |  |  |  |  |    "+ fg.rs)
sleep(0.5)
print(fg(202)+"  |  |  |  | "+fg(226)+")_) "+fg(202)+"|  |  |  |"+fg(199)+"))"+fg(202)+"|  |  |  |  |  |    "+ fg.rs)
sleep(0.5)
print(fg(202)+"  |  |  |  |  |  |  |  |  "+fg(199)+"(/ "+fg(202)+"|  |  |  |  |  |    "+ fg.rs)
sleep(0.5)
print(fg(202)+"  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |    "+ fg.rs)